### ISSUE TITLE
Coversion to json crashes if 

### ISSUE THREAD

**Issue by mhsano** [pybel/pybel#121]
Hi,

The conversion to json crashes if a required document metadata field is not available. (eg. ContactInfo)

We have a many BEL files from commercial vendors and some do not have all requiered metadata fields. Is it possible tpo change the error message generatd by the metadata parser into a warning and fill the missing metadata fiels with an "NA" value?

**Comment by cthoyt** [comment]
Can you provide the BEL document (maybe just the metadata section from the top) and the code that produced the error?

This should be an easy fix that I can have done tomorrow.

**Comment by mhsano** [comment]
##################################################################################
# Document Properties Section

SET DOCUMENT Name = "MB interactions"
SET DOCUMENT Description = ""
SET DOCUMENT Version = "1.0"
SET DOCUMENT Authors = "Vendor1"

##################################################################################

Error:

ERROR:pybel.graph:Missing required document metadata: ContactInfo
ERROR:pybel.graph:Missing required document metadata not filled: Description


Exception:

Traceback (most recent call last):
  File "/opt/Software/anaconda3/bin/pybel", line 11, in <module>
    load_entry_point('PyBEL==0.3.8', 'console_scripts', 'pybel')()
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/PyBEL-0.3.8-py3.5.egg/pybel/cli.py", line 93, in convert
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/PyBEL-0.3.8-py3.5.egg/pybel/io.py", line 207, in to_json
  File "/opt/Software/anaconda3/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/opt/Software/anaconda3/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: MissingMetadataException('Description',) is not JSON serializable


regards,
mh

**Comment by mhsano** [comment]
Didn't want to close it...

**Comment by cthoyt** [comment]
Great this isn't a very helpful error message. I'm afk but I believe this may have been a mistake of me forgetting to put a call to the super constructor in the __init__ of the Exception in question. This makes lots of serialization (including pickle) act wonky. Will have a fix on PyPI as v0.3.9 tomorrow.

**Comment by cthoyt** [comment]
Oh that was a typo. This *is* a very helpful message haha

**Comment by cthoyt** [comment]
Closed with v0.3.9 release
