### ISSUE TITLE
Conversion to CX format crashes

### ISSUE THREAD

**Issue by mhsano** [pybel/pybel#152]
Hi,

the conversion to CX format crashes with the following error message.
I am using ByBEL Version: 0.4.2
Regrads,

INFO:pybel:Outputting CX to t.cx
Traceback (most recent call last):
  File "/opt/Software/anaconda3/bin/pybel", line 11, in <module>
    sys.exit(main())
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/pybel/cli.py", line 106, in convert
    to_cx(g, cx)
  File "/opt/Software/anaconda3/lib/python3.5/site-packages/pybel/cx.py", line 31, in to_cx
    json.dump(json_graph, file, ensure_ascii=False)
  File "/opt/Software/anaconda3/lib/python3.5/json/__init__.py", line 179, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'

**Comment by cthoyt** [comment]
Thanks for the heads up. This was a simple error on my part on line 59 of `pybel.cli`. I forgot to include `type=click.File('w')` as one of the keyword arguments in the CX argument parser. I have a couple other housekeeping things to do before making a release for 0.4.3, but a fix will be pushed to the develop branch ASAP.
