### ISSUE TITLE
Directory creation could be wrapped in try/except

### ISSUE THREAD

**Issue by bgyori** [pybel/pybel#284]
When running INDRA by multiple workers in a "clean" environment, upon importing pybel, the workers occasionally run into errors because they try to create a folder that already exists:
https://github.com/pybel/pybel/blob/develop/src/pybel/constants.py#L44-L46
Could this `mkdir` be wrapped in try/except and just print a warning if it fails?

**Comment by cthoyt** [comment]
That's a really interesting problem! Are you getting a `FileExistsError`? (ref: https://docs.python.org/3/library/os.html#os.mkdir) 

I think [`os.makedirs`](https://docs.python.org/3/library/os.html#os.makedirs) solves this, but it's only Python3...

We can definitely wrap this line with try/catch, but I'd want to be as specific with the error message as possible!

**Comment by bgyori** [comment]
```python
Traceback (most recent call last):
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
worker.init_process()
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
self.load_wsgi()
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
self.wsgi = self.app.wsgi()
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
return self.load_wsgiapp()
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
return util.import_app(self.app_uri)
File "/sw/miniconda/lib/python3.5/site-packages/gunicorn/util.py", line 352, in import_app
__import__(module)
File "/sw/indra/rest_api/api.py", line 5, in <module>
from indra.sources import trips, reach, bel, biopax
File "/sw/indra/indra/sources/bel/__init__.py", line 1, in <module>
from .bel_api import process_ndex_neighborhood
File "/sw/indra/indra/sources/bel/bel_api.py", line 9, in <module>
from .pybel_processor import PybelProcessor
File "/sw/indra/indra/sources/bel/pybel_processor.py", line 4, in <module>
import pybel.constants as pc
File "/sw/miniconda/lib/python3.5/site-packages/pybel/__init__.py", line 99, in <module>
from . import canonicalize, constants, examples, examples, io, struct
File "/sw/miniconda/lib/python3.5/site-packages/pybel/canonicalize.py", line 10, in <module>
from .constants import *
File "/sw/miniconda/lib/python3.5/site-packages/pybel/constants.py", line 46, in <module>
mkdir(PYBEL_DIR)
```

**Comment by cthoyt** [comment]
Before we call this one closed, what do you think we should do about https://github.com/pybel/pybel/blob/develop/src/pybel/constants.py#L68-L75, which involves creating a file and writing to it?

**Comment by bgyori** [comment]
That's more tricky. The writing could be made safe with try/except but reading can also fail (or return inconsistent results) if another worker is still writing the same file and it's much harder to protect against that.

**Comment by cthoyt** [comment]
It might actually not be smart to create this file if it doesn't already exist. I put this by Christian's recommendation to make it more obvious how to edit the configuration, but I think better documentation might suffice :)
