### ISSUE TITLE
INDRA's PyBEL example fails

### ISSUE THREAD

**Issue by scolby33** [pybel/pybel#374]
It seems like `pybel.io.lines.parse_lines` lost an argument `identifier_validation` that INDRA was using.

I did a standard install in a clean CPython 3.7.1 virtual environment: `pip install indra pybel`

```
>>> from indra.sources import bel
>>> bel_processor = bel.process_pybel_neighborhood(['KRAS', 'BRAF'])
INFO: [2019-01-07 14:52:44] pybel.io.lines - Loading from path: /Users/scott/dev/indra/indra/sources/bel/../../../data/large_corpus.bel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/dev/indra/indra/sources/bel/api.py", line 106, in process_pybel_neighborhood
    bp = process_belscript(network_file)
  File "/Users/scott/dev/indra/indra/sources/bel/api.py", line 214, in process_belscript
    pybel_graph = pybel.from_path(file_name, **kwargs)
  File "/Users/scott/.virtualenvs/indra/lib/python3.7/site-packages/pybel/io/lines.py", line 48, in from_path
    parse_lines(graph=graph, lines=lines, **kwargs)
TypeError: parse_lines() got an unexpected keyword argument 'identifier_validation'
```

See related sorgerlab/indra#769

**Comment by cthoyt** [comment]
Addressed with https://github.com/sorgerlab/indra/pull/770
