### ISSUE TITLE
UnicodeDecodeError with Windows

### ISSUE THREAD

**Issue by YojanaGadiya** [pybel/pybel#427]
While loading the graph from Windows, there seem to be encoding errors. I wonder if there is any way to add an encoding option while loading the graph using pybel.load( ) method.

**Comment by cthoyt** [comment]
Please provide code + data example for reproducibility

**Comment by cthoyt** [comment]
@YojanaGadiya I'm going to close this issue later today if there's no ongoing discussion

**Comment by YojanaGadiya** [comment]
@cthoyt Sorry for getting back so late. I seem to be struggling with the same issue now. To give some background, I created a graph on BEL and load it via Windows. I get the following error : 

```
>>> import pybel
>>> graph = pybel.load('data/graph/processed/graph.bel.nodelink.json.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Yojana.Gadiya\Anaconda3\envs\tmp\lib\site-packages\pybel\io\api.py", line 60, in load
    return importer(path, **kwargs)
  File "C:\Users\Yojana.Gadiya\Anaconda3\envs\tmp\lib\site-packages\pybel\io\nodelink.py", line 116, in from_nodelink_gz
    return from_nodelink(json.load(file))
  File "C:\Users\Yojana.Gadiya\Anaconda3\envs\tmp\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Yojana.Gadiya\Anaconda3\envs\tmp\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 95265: character maps to <undefined>
```

Loading it on Mac works fine, but on Windows, it causes this issue. Any idea on how this issue could be fixed? I needed it for code reproducibility over multiple OS-

Thank You.
